name: leotena
description: Leotena — Premium Android movies, series & live channels streaming app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_tts: ^4.2.5
  http: ^1.2.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
